[Global]
RunMode = "release"

[Log]
Dir = "logs"
Level = "INFO"
Output = "stdout"

[HTTP]
Host = "0.0.0.0"
Port = 17000
CertFile = ""
KeyFile = ""
PrintAccessLog = false
PProf = false
ExposeMetrics = true
ShutdownTimeout = 30
MaxContentLength = 67108864
ReadTimeout = 20
WriteTimeout = 40
IdleTimeout = 120

[HTTP.ShowCaptcha]
Enable = false

[HTTP.APIForAgent]
Enable = true

[HTTP.APIForService]
Enable = false
[HTTP.APIForService.BasicAuth]
user001 = "ccc26da7b9aba533cbb263a36c07dcc5"

[HTTP.JWTAuth]
AccessExpired = 1500
RefreshExpired = 10080
RedisKeyPrefix = "/jwt/"

[HTTP.ProxyAuth]
Enable = false
HeaderUserNameKey = "X-User-Name"
DefaultRoles = ["Standard"]

[HTTP.TokenAuth]
Enable = true

[HTTP.RSA]
OpenRSA = false

[DB]
# 使用 MySQL
DBType = "mysql"
DSN = "n9e:n9e@2024@tcp(mysql:3306)/n9e?charset=utf8mb4&parseTime=True&loc=Local"
Debug = false
MaxLifetime = 7200
MaxOpenConns = 150
MaxIdleConns = 50

[Redis]
Address = "redis:6379"
RedisType = "standalone"

[Alert]
[Alert.Heartbeat]
IP = ""
Interval = 1000
EngineName = "default"

[Center]
MetricsYamlFile = "./etc/metrics.yaml"
I18NHeaderKey = "X-Language"

[Center.AnonymousAccess]
PromQuerier = true
AlertDetail = true

[Pushgw]
LabelRewrite = true
ForceUseServerTS = true

[[Pushgw.Writers]]
Url = "http://prometheus:9090/api/v1/write"

[Ibex]
Enable = true
RPCListen = "0.0.0.0:20090"

